import Recoil from "@/store/Recoil";
import "./styles/globals.css";
import StyledComponentsRegistry from "./styles/registry";

export const metadata = {
  title: "Lotto 번호 뽑기",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <h1 className="text-center text-4xl mt-6">로또 번호 뽑기</h1>
        <Recoil>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </Recoil>
      </body>
    </html>
  );
}
